services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-wrapped-backend
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      # Spotify API credentials - REQUIRED
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      # Spring Boot configuration
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-default}
      # JVM options for production
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    networks:
      - spotify-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: spotify-wrapped-frontend
    ports:
      - "127.0.0.1:3000:80"
    networks:
      - spotify-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  spotify-network:
    driver: bridge
