spring:
  application:
    name: spotify-wrapped
  jackson:
    serialization:
      indent-output: true
    default-property-inclusion: non_null
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID:}
            client-secret: ${SPOTIFY_CLIENT_SECRET:}
            scope:
              - user-top-read
              - user-read-recently-played
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Spotify
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spotify:
  api:
    base-url: https://api.spotify.com/v1
    auth-url: https://accounts.spotify.com/api/token
    client-id: ${SPOTIFY_CLIENT_ID:}
    client-secret: ${SPOTIFY_CLIENT_SECRET:}
    default-limit: 5

logging:
  level:
    org.adarssh: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
